name: weather
description: "A Flutter Weather app."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator:
  freezed: ^2.4.5

  # Location
  geolocator:
  geocoding:

  # State management
  freezed_annotation:
  json_annotation:
  equatable:
  bloc:
  flutter_bloc:
  bloc_concurrency:
  provider:
  shared_preferences:

  # Networking
  retrofit:
  fresh_dio:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner:
  retrofit_generator:

flutter:
  uses-material-design: true